name: Detect Push on Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print a message
        run: echo "A push has been detected on the main branch!"

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/SSHKey
          chmod 600 ~/.ssh/SSHKey
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

      - name: Run git pull on remote server
        run: |
          ssh -o StrictHostKeyChecking=no aarons@$SSH_HOST << 'EOF'
            cd /home/admin/ProjetCodeSource  # Remplacez par le chemin du projet sur le serveur
            git pull origin main  # Effectuer un git pull sur la branche main
          EOF
      