name: Detect Push on Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print a message
        run: echo "A push has been detected on the main branch!"

      - name: Update packages
        run: |
          sudo apt-get update && sudo apt-get upgrade -y

      - name: Install OpenSSH client
        run: sudo apt-get install -y openssh-client

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > C:/Users/Aaron/.ssh
          chmod 600 C:/Users/Aaron/.ssh




