name: Detect Push on Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print a message
        run: echo "A push has been detected on the main branch!"

      - name: Build Docker image
        run: |
          docker build -t deploy-image .

      - name: Run Docker container for deployment
        run: |
          docker run --rm \
            -e SSH_PRIVATE_KEY="${{ secrets.SSH_PRIVATE_KEY }}" \
            -e SSH_HOST="${{ secrets.SSH_HOST }}" \
            deploy-image /bin/bash -c "
              # Copier la clé SSH dans le conteneur
              echo \"\$SSH_PRIVATE_KEY\" > /root/.ssh/SSHKey && \
              chmod 600 /root/.ssh/id_rsa && \
              
              # Supprimer la clé privée après utilisation pour des raisons de sécurité
              trap 'rm -rf /root/.ssh' EXIT && \
              
              # Accepter les hôtes inconnus pour la première connexion SSH
              ssh-keyscan -H \$ >> /root/.ssh/known_hosts && \
              
              # Se connecter en SSH et effectuer un git pull
              ssh -o StrictHostKeyChecking=no user@\$AWS_SERVER_IP << 'EOF'
                cd /path/to/your/project  # Remplacez par le chemin de votre projet sur le serveur
                git pull origin main  # Effectuer un git pull sur la branche main
              EOF
            "





